#
# Configuration for finding longest ORF
#  that requires:
#  - start codon: sequence that indicates where ORF begins
#  - stop codon: sequence that indicates where ORF ends
#  - reverse: search the reverse sequence
#  - direct: search the given sequence (at least this and reverse must be used)
#  - min: minimum size of sequence
#  - max: maximum size of sequence
orf:
  stop_codon:
    - tag
    - taa
    - tga
  start_codon:
    - atg
  reverse: true
  direct: true
  min: 100
#
# prune identical:
#  - use_worst: false to keep best redundant result, true otherwise
#  - first: column to use in first iteration to filter out the results
#  - list: columns that identify redundant results (if they have the same value)
#
# note: columns that are calculated can only be used in list and never at first.
#  they are only calculated after to reduce memory and cpu usage.
prune_identical:
  use_worst: false
  first: sseqid
  list:
    - nt_aligned_seq
#
codon_table: 1
#
# output directory options:
#  - dir: output directory's name
#  - ext: extension for blast files
output:
  dir: output
  extension: .out
  intermediate: intermediate
  blast_results: blast_results
  fastas: fasta_files

debug:
  level: "info"
  file: output/log.txt
  show_stdout_if_file: true

config:
  user: config/user.yml
#
# removes blanks lines
clean_output: true

#
# value for filtering the results on the identity
#  column, i.e. only above 40% in case the config is .40
identity:
  min: .40 # value between 0 and 1
  max: 1   # value between 0 and 1

#
# Directory that holds all database files in blastdb format
#  if you need to convert a fasta file to this format, you
#  can use the tool from blast+:
#    $ makeblastdb
#  or put the files in db_and_queries/import_db and run the
#  the script that is in that folder
db:
  parent: db_and_queries/db
  # In case list is empty it will use all blast dbs in parent
  #  that have a .nhr extension
  list:
#
# Directories that holds all queries in form of fasta files
# All query files must have as extensions:
#  .fasta .query .fas .fna
query:
  parent: db_and_queries
  # It supports multiple folders holding the queries by
  #  adding new lines in 'folders' options
  # note: all new lines must follow indentation and start
  #  with a dash '-' (without quotes)
  folders:
    - queries

#
# how to format the output file. by default should show all columns
format:
  outfmt: 6

  specifiers:
    qseqid: "means Query Seq-id"
    evalue: "means Expect value"
    pident: "means Percentage of identical matches"
    qcovs: "means Query Coverage Per Subject"
    qgi: "means Query GI"
    qacc: "means Query accesion"
    sseqid: "means Subject Seq-id"
    sallseqid: "means All subject Seq-id(s), separated by a ';'"
    sgi: "means Subject GI"
    sallgi: "means All subject GIs"
    sacc: "means Subject accession"
    sallacc: "means All subject accessions"
    qstart: "means Start of alignment in query"
    qend: "means End of alignment in query"
    sstart: "means Start of alignment in subject"
    send: "means End of alignment in subject"
    bitscore: "means Bit score"
    score: "means Raw score"
    length: "means Alignment length"
    nident: "means Number of identical matches"
    mismatch: "means Number of mismatches"
    positive: "means Number of positive-scoring matches"
    gapopen: "means Number of gap openings"
    gaps: "means Total number of gap"
    ppos: "means Percentage of positive-scoring matches"
    frames: "means Query and subject frames separated by a '/'"
    qframe: "means Query frame"
    sframe: "means Subject frame"
    btop: "means Blast traceback operations (BTOP)"
    staxids: "means unique Subject Taxonomy ID(s), separated by a ';'(in numerical order)"
    sscinames: "means unique Subject Scientific Name(s), separated by a ';'"
    scomnames: "means unique Subject Common Name(s), separated by a ';'"
    sblastnames: "means unique Subject Blast Name(s), separated by a ';' (in alphabetical order)"
    sskingdoms: "means unique Subject Super Kingdom(s), separated by a ';' (in alphabetical order)"
    stitle: "means Subject Title"
    salltitles: "means All Subject Title(s), separated by a '<>'"
    sstrand: "means Subject Strand"
    qcovhsp: "means Query Coverage Per HSP"
    qseq: "means Aligned part of query sequence"
    sseq: "means Aligned part of subject sequence"
